name: asar-Packer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Pack app.asar
      run: |
        ${{ secrets.installs }}
        ${{ secrets.runapp }}
        ${{ secrets.commandpack }}
    - name: Upload app.asar
      uses: actions/upload-artifact@v1.0.0
      with:
         name: app.asar
         path: app.asar
      
