name: asar-Packer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pack app.asar
      run: |
        npm install -g asar
        mkdir app
        cp style.css app/style.css
        cp renderer.js app/renderer.js
        cp package.json app/package.json
        cp main.js app/main.js
        cp index.html app/index.html
        cp License.rtf app/License.rtf
        ls app
        asar pack app app.asar
    - name: Upload app.asar
      uses: actions/upload-artifact@v1.0.0
      with:
         name: app.asar
         path: app.asar
      
